const fs = require('fs');
const path = require('path');

const cssPath = path.join(__dirname, 'frontend', 'colleges', 'punjab', 'lovely-professional-university', 'lovely-professional-university.css');
const headerJsPath = path.join(__dirname, 'frontend', 'shared', 'header.js');
const footerJsPath = path.join(__dirname, 'frontend', 'shared', 'footer.js');

const cssStr = fs.readFileSync(cssPath, 'utf8');
const headerJsStr = fs.readFileSync(headerJsPath, 'utf8');
const footerJsStr = fs.readFileSync(footerJsPath, 'utf8');

const sharedJsStr = headerJsStr + '\n\n' + footerJsStr + '\n\n/* --- END SHARED --- */\n\n';

const newGenUtils = `// AUTO-GENERATED: DO NOT EDIT THIS FILE DIRECTLY TO UPDATE CSS/JS.
// Updates should be made in shared files or the generator and then re-embedded.

function getTabsHtml(category) {
    if (category === "Medical") {
        return \`
    <nav class="lpu-tabs-nav" id="lpu-tabs-nav">
        <div class="container">
            <div class="lpu-tabs" id="lpu-tabs">
                <button class="lpu-tab active" data-tab="overview">Overview</button>
                <button class="lpu-tab" data-tab="courses">Courses &amp; Fees</button>
                <button class="lpu-tab" data-tab="admission">Admission</button>
                <button class="lpu-tab" data-tab="placements">Internships</button>
                <button class="lpu-tab" data-tab="reviews">Reviews</button>
                <button class="lpu-tab" data-tab="gallery">Gallery</button>
            </div>
        </div>
    </nav>\`;
    } else {
        return \`
    <nav class="lpu-tabs-nav" id="lpu-tabs-nav">
        <div class="container">
            <div class="lpu-tabs" id="lpu-tabs">
                <button class="lpu-tab active" data-tab="overview">Overview</button>
                <button class="lpu-tab" data-tab="courses">Courses &amp; Fees</button>
                <button class="lpu-tab" data-tab="admission">Admission</button>
                <button class="lpu-tab" data-tab="fees">Fees &amp; Scholarships</button>
                <button class="lpu-tab" data-tab="placements">Placements</button>
                <button class="lpu-tab" data-tab="reviews">Reviews</button>
                <button class="lpu-tab" data-tab="gallery">Gallery</button>
            </div>
        </div>
    </nav>\`;
    }
}

const CSS_CONTENT = ${JSON.stringify(cssStr)};
const SHARED_JS_CONTENT = ${JSON.stringify(sharedJsStr)};

function getFullCss() {
    return CSS_CONTENT;
}

function getJsContent(colName, colAbbr, colSlug) {
    const bottomJs = \`/* \${colName} (\${colAbbr}) — NextCampus College Detail JS */
document.addEventListener('DOMContentLoaded', () => { setupTabs(); setupStickyHeader(); setupMobileApplyBar(); });
function setupTabs() {
    const tabs = document.querySelectorAll('.lpu-tab');
    const panels = document.querySelectorAll('.lpu-panel');
    function switchTab(n) {
        tabs.forEach(t => t.classList.remove('active'));
        panels.forEach(p => p.classList.remove('active'));
        const t = [...tabs].find(t => t.dataset.tab === n);
        if (t) t.classList.add('active');
        const p = document.getElementById('panel-' + n);
        if (p) { p.classList.add('active'); p.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
    }
    tabs.forEach(tab => tab.addEventListener('click', () => switchTab(tab.dataset.tab)));
    document.querySelectorAll('.btn-view-tab').forEach(btn => btn.addEventListener('click', () => switchTab(btn.dataset.target)));
}
function setupStickyHeader() {
    const s = document.getElementById('lpu-sticky-header');
    const h = document.getElementById('lpu-hero');
    const n = document.getElementById('lpu-tabs-nav');
    if (!s || !h) return;
    window.addEventListener('scroll', () => {
        const scrollY = window.pageYOffset;
        if (scrollY > h.offsetTop + h.offsetHeight) { s.classList.add('visible'); if (n) n.style.top = s.offsetHeight + 'px'; }
        else { s.classList.remove('visible'); if (n) n.style.top = '0px'; }
    }, { passive: true });
}
function setupMobileApplyBar() {
    const b = document.getElementById('mobile-apply-bar');
    if (!b) return;
    window.addEventListener('scroll', () => { if (window.innerWidth <= 768) b.style.display = window.pageYOffset > 300 ? 'block' : 'none'; }, { passive: true });
}
\`;
    return SHARED_JS_CONTENT + bottomJs;
}

module.exports = { getTabsHtml, getJsContent, getFullCss };
`;

fs.writeFileSync(path.join(__dirname, 'gen_utils.js'), newGenUtils);
console.log('gen_utils.js successfully rebuilt with inline CSS and JS!');
